apps/cart/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from apps.cart import views

urlpatterns = [
    url(r'^add$', views.AddCartView.as_view(), name='add'),
    url(r'^update$', views.CartUpdateView.as_view(), name='update'),
    url(r'^delete$', views.CartDeleteView.as_view(), name='delete'),
    url(r'^$', views.CartInfoView.as_view(), name='info'),
]

apps/goods/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from apps.goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(), name='index'),
    # http://127.0.0.1:8000/detail/商品id
    url(r'^detail/(\d+)$', views.DetailView.as_view(), name='detail'),
    # /list/类别id/第几页数据
    url(r'^list/(\d+)/(\d+)$', views.ListView.as_view(), name='list'),
]

apps/orders/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from apps.orders import views

urlpatterns = [
    url(r'^place$', views.PlaceOrdersView.as_view(), name='place'),
    # orders/commit
    url(r'^commit$', views.CommitOrdersView.as_view(), name='commit'),
]

apps/users/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from apps.users import views

urlpatterns = [
    # http://127.0.0.1:8000/users/register
    # url(r'^register$', views.register, name='register'),
    # url(r'^do_register$', views.do_register, name='do_register'),

    url(r'^register$', views.RegisterView.as_view(), name='register'),

    # http://127.0.0.1:8000/users/active/eyJhbGciOiJIUzI1NiIsImlhdCI6MTUyNDMwMTQ1MiwiZXhwIjoxNTI0Mzg3ODUyfQ.eyJjb25maXJtIjoxNH0.LyqYBADhhKsoK8pPFi66PesPAF-P-bZKtCb_DolxeOI
    url(r'^active/(.+)$', views.ActiveView.as_view(), name='active'),

    # 127.0.0.1:8000/users/login
    url(r'^login$', views.LoginView.as_view(), name='login'),

    url(r'^logout$', views.LogoutView.as_view(), name='logout'),

    url(r'^address$', views.UserAddressView.as_view(), name='address'),

    url(r'^orders/(\d+)$', views.UserOrderView.as_view(), name='orders'),
    # url(r'^orders$', login_required(views.UserOrderView.as_view()), name='orders'),

    url(r'^$', views.UserInfoView.as_view(), name='info'),


]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^orders/', include('apps.orders.urls', namespace='orders')),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('apps.goods.urls', namespace='goods')),
    # 包含tinymce urls配置文件
    url(r'^tinymce/', include('tinymce.urls')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from django_redis import get_redis_connection
from redis.client import StrictRedis

from apps.goods.models import GoodsSKU
from utils.commont import LoginRequiredMixin


class AddCartView(View):
    """添加到购物车"""

    def post(self, request):

        # 判断用户是否登陆
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请先登陆'})

        # 接收数据：user_id，sku_id，count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验参数all()

        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '参数不能为空'})

        # 判断商品是否存在
        sku = None
        try:
            sku = GoodsSKU.objects.filter(id=sku_id)[0]
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 3, 'errmsg': '没有次商品'})


        # 判断count是否是整数

        try:
            count = int(count)
        except:
            return JsonResponse({'code': 4, 'errmsg': '数量需为整数'})

        # 判断库存
        strict_redis = get_redis_connection() # type: StrictRedis
        key = 'cart_{}'.format(request.user.id)
        val = strict_redis.hget(key, sku_id)
        if val:
            count += int(val)
        if sku.stock < count:
            return JsonResponse({'code': 5, 'errmsg': '库存不够'})

        # 操作redis数据库存储商品到购物车

        strict_redis.hset(key, sku_id, count)

        # 查询购物车中商品的总数量
        total_count = 0
        vals = strict_redis.hvals(key)
        for val in vals:
            total_count += int(val)

        # json方式响应添加购物车结果
        return JsonResponse({'code': 0, 'total_count': total_count})


class CartInfoView(LoginRequiredMixin, View):
    def get(self, request):
        user_id = request.user.id
        skus = []
        total_count = 0
        total_amount = 0
        key = 'cart_{}'.format(user_id)
        strict_redis = get_redis_connection() # type: StrictRedis
        sku_ids = strict_redis.hkeys(key)
        for sku_id in sku_ids:
            sku = GoodsSKU.objects.get(id=int(sku_id))
            count = int(strict_redis.hget(key, sku_id))
            amount = count * sku.price
            sku.count = count
            sku.amount = amount
            skus.append(sku)
            total_count += count
            total_amount += amount

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount,
        }
        return render(request, 'cart.html', context)


class CartUpdateView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请登陆'})
        if not all([sku_id, count]):
            return JsonResponse({'code': 2, 'errmsg': '参数不能为空'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 3, 'errmsg': '商品不存在'})
        try:
            count = int(count)
        except:
            return JsonResponse({'code': 4, 'errmsg': '参数需为整数'})
        if count > sku.stock:
            return JsonResponse({'code': 5, 'errmsg': '库存不够'})
        strict_redis = get_redis_connection() # type: StrictRedis
        key = 'cart_{}'.format(request.user.id)
        strict_redis.hset(key, sku_id, count)
        # 查询购物车中商品的总数量
        total_count = 0
        vals = strict_redis.hvals(key)
        for val in vals:
            total_count += int(val)

        # json方式响应添加购物车结果
        return JsonResponse({'code': 0, 'total_count': total_count})


class CartDeleteView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        if not request.user.is_authenticated():
            return JsonResponse({'code': 1, 'errmsg': '请登陆'})
        if not sku_id:
            return JsonResponse({'code': 2, 'errmsg': '商品id不能为空'})
        strict_redis = get_redis_connection() # type: StrictRedis
        key = 'cart_{}'.format(request.user.id)
        strict_redis.hdel(key, sku_id)

        # 查询购物车中商品的总数量
        total_count = 0
        vals = strict_redis.hvals(key)
        for val in vals:
            total_count += int(val)

        # json方式响应添加购物车结果
        return JsonResponse({'code': 0, 'total_count': total_count})

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}天天生鲜-首页{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {#  顶部js导入 #}
    {% block top_js %}
    {% endblock %}

</head>
<body>

{# 界面顶部的信息栏 #}
{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">

                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'users:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:register' %}">注册</a>
                    </div>
                {% endif %}


                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'users:info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:info' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'users:orders' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{# 搜索栏 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <form method="get" action="/search">
            <div class="search_con fl">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </div>
        </form>
        <div class="guest_cart fr">
            <a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock %}


{# 主体内容 #}
{% block body %}
{% endblock %}

{# 版权信息 #}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

{# 界面底部js #}
{% block bottom_js %}
{% endblock %}

</body>
</html>

templates/base_user_center.html
{# 用户中心父模板: 用户中心的3个子界面 #}
{% extends 'base_no_cart.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block page_title %}
    用户中心
{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        {# 左侧部分内容 #}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:info' %}"{% if which_page == 1 %} class="active"{% endif %} >· 个人信息</a></li>
                <li><a href="{% url 'users:orders' 1 %}"{% if which_page == 2 %}class="active"{% endif %} >· 全部订单</a></li>
                <li><a href="{% url 'users:address' %}"{% if which_page == 3 %} class="active"{% endif %} >· 收货地址</a></li>
            </ul>
        </div>

        {# 右侧部分内容 #}
        {% block right_body %}
        {% endblock %}

    </div>
{% endblock %}

templates/detai.html
{% extends 'base.html' %}

{% block title %}
    天天生鲜-商品详情
{% endblock %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">

                    {# 显示所有类别 #}
                    {% for category in categories %}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="{% url 'goods:list' sku.category.id 1 %}">{{ sku.category.name }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl">
            <img height="300px" width="300px"
                 src="{{ sku.default_image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.title }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unit }}</span>
            </div>

            {# 其他规格商品显示 #}
            {% if other_skus %}
                <div>
                    <p>其他规格:</p>
                    <ul>
                        {% for sku in other_skus %}
                            <li><a href="{% url 'goods:detail' sku.id %}"
                                   style="text-decoration:none">{{ sku.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <form method="post" action="{% url 'orders:place' %}">
                {% csrf_token %}
                <input type="hidden" name="sku_ids" value="{{ sku.id }}">
                <div class="goods_num clearfix">
                    <div class="num_name fl">数 量：</div>
                    <div class="num_add fl">
                        <input type="text" class="num_show fl" name="count" value="1">
                        <a href="javascript:;" class="add fr">+</a>
                        <a href="javascript:;" class="minus fr">-</a>
                    </div>
                </div>
                <div class="total">总价：<em>{{ sku.price }} 元</em></div>
                <div class="operate_btn">
                    <input type="submit" class="buy_btn" value="立即购买">
                    <a href="javascript:;" class="add_cart" id="add_cart" sku_id="{{ sku.id }}">加入购物车</a>
                </div>
            </form>


        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>

                    {# 显示当前类别下的新品 #}
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img
                                    src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="#">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ sku.spu.desc|safe }}</dd>
                </dl>
            </div>

        </div>
    </div>

{% endblock %}

{% block bottom_js %}
    {% load staticfiles %}
    {% csrf_token %}

    <div class="add_jump"></div>

    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        update_goods_info();

        function update_goods_info() {
            var count = $('.num_show').val();
            var price = $('.show_pirze').children('em').text();
            var amount = parseInt(count) * parseFloat(price);
            $('.total').children('em').html(amount.toFixed(2) + '元');
        };

        $('.add').click(function () {
            var count = $('.num_show').val();
            count = parseInt(count);
            count++;
            $('.num_show').val(count);
            update_goods_info();
        });

        $('.minus').click(function () {
            var count = $('.num_show').val();
            count = parseInt(count);
            if (count > 1) {
                count--;
                $('.num_show').val(count);
                update_goods_info();
            }

        });

        $('.num_show').blur(function () {
            var count = $('.num_show').val();
            if (parseInt(count) < 1 || count.trim().length == 0 || isNaN(count)) {
                count = 1;
            }
            $('.num_show').val(parseInt(count));
            update_goods_info();
        });

        $('#add_cart').click(function () {
            var count = $('.num_show').val();
            var sku_id = $(this).attr('sku_id')
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            {#            alert(count + '====' + sku_id)#}

            var params = {
                sku_id: sku_id,
                count: count,
                csrfmiddlewaretoken: csrf
            };

            $.post('/cart/add', params, function (date) {
                if (date.code == 0) {
                    var total_count = date.total_count;

                    $('#show_count').html(total_count);
                } else {
                    alert(date.errmsg)
                }
            });
        });


        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
        $('#add_cart').click(function () {
            $(".add_jump").stop().animate({
                    'left': $to_y + 7,
                    'top': $to_x + 7
                },
                "fast", function () {
                    $(".add_jump").fadeOut('fast', function () {
                        $('#show_count').html();
                    });

                });
        })
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    天天生鲜-首页
{% endblock %}

{% block top_js %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for category in categories %}
                <li><a href="{% url 'goods:list' category.id 1 %}" class="{{ category.logo }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {% for slide_sku in slide_skus %}
                    <a href="{% url 'goods:detail' slide_sku.sku.id %}"><li><img src="{{ slide_sku.image.url }}" alt="幻灯片"></li></a>
                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {% for promotion in promotions %}
                <a href="{{ promotion.url }}"><img src="{{ promotion.image.url }}"></a>
            {% endfor %}

        </div>
    </div>

    {% for category in categories %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model01">{{ category.name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for c_sku in category.text_skus %}
                        <a href="{% url 'goods:detail' c_sku.sku.id %}">{{ c_sku.sku.name }}</a>
                    {% endfor %}

                </div>
                <a href="{% url 'goods:list' category.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{{ category.image.url }}"></div>
                <ul class="goods_list fl">
                    {% for c_sku in category.image_skus %}
                        <li>
                            <h4><a href="{% url 'goods:detail' c_sku.sku.id %}">{{ c_sku.sku.name }}</a></h4>
                            <a href="{% url 'goods:detail' c_sku.sku.id %}"><img src="{{ c_sku.sku.default_image.url }}"></a>
                            <div class="prize">¥ {{ c_sku.sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    {% endfor %}

{% endblock %}

{% block bottom_js %}
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    <script type="text/javascript">

        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '{{ cart_count }}';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    天天生鲜-商品列表
{% endblock %}

{% block body %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">

                     {# 显示所有的类别 #}
                    {% for category in categories %}
                         {# 默认跳转到某个分类商品列表的第一页 #}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="{% url 'goods:index' %}">全部分类</a>
        <span>></span>

         {# 显示当前类别 #}
        <a href="{% url 'goods:list' category.id 1 %}">{{ category.name }}</a>

    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>

                     {#显示类别新品#}
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img
                                    src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' new_sku.id %}">
                                {{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">

                 {# 显示排序条件: 并设置当前选中的是哪一项 #}
                <a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price"
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot"
                   {% if sort == 'hot' %}class="active"{% endif %}>人气</a>

            </div>

            <ul class="goods_type_list clearfix">

                 {#  #}显示分页商品
                {% for sku in page %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}">
                            <img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">
                            {{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}

            </ul>

            <div class="pagenation">

                 显示分页信息
                {% if page.has_previous %}
                    <a href="{% url 'goods:list' category.id page.previous_page_number %}?sort={{ sort }}"
                    >上一页</a>
                {% endif %}

                {% for index in page_list %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}"
                       {% if index == page.number %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}

                {% if page.has_next %}
                    <a href="{% url 'goods:list' category.id page.next_page_number %}?sort={{ sort }}"
                    >下一页</a>
                {% endif %}

            </div>

        </div>
    </div>

{% endblock %}

templates/list2.html
{% extends 'base.html' %}

{% block title %}
    天天生鲜-商品列表
{% endblock %}

{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">

                    {# 显示类别 #}
                    {% for category in categories %}
                        <li><a href="{% url 'goods:list' category.id 1 %}"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="{% url 'goods:list' category.id 1 %}">{{ category.name }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}">
                                <img src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="#">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'goods:list' category.id 1 %}?sort=default" {% if sort == 'default' %}
                   class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price" {% if sort == 'price' %}
                   class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == 'hot' %}
                   class="active"{% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for sku in page %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">
                {% if page.has_previous %}
                    <a href="{% url 'goods:list' category.id page.previous_page_number %}?sort={{ sort }}"
                    >上一页</a>
                {% endif %}
                {% for index in page_list %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}" class="active">{{ index }}</a>
                {% endfor %}
                {% if page.has_next %}
                    <a href="{% url 'goods:list' category.id page.next_page_number %}?sort={{ sort }}"
                    >下一页></a>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}